name: Bug Report
description: Something does not work as expected
title: "[BUG] "
labels: [ "bug" ]
type: bug
body:
  - type: markdown
    attributes:
      value: App bug report

  - type: checkboxes
    id: checklist
    attributes:
      label: Guidelines
      description: Confirm before submitting
      options:
        - label: I have searched the issue tracker for [open](https://github.com/Droid-ify/client/issues) and [closed](https://github.com/Droid-ify/client/issues?q=is%3Aissue+is%3Aclosed) issues that are related to the bug report I want to file, without success.
          required: true
        - label: I'm on the [latest](https://github.com/Droid-ify/client/releases/latest) released version.
          required: true

  - type: textarea
    id: description
    attributes:
      label: What happened
      description: Describe the bug
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the bug. The issue might be closed if we fail to reproduce it.
      placeholder: |
        1. Open the app and go to...
        2. Tap on...
        3. See the error

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?
      placeholder: Normally it would...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots here if relevant to the bug report

  - type: input
    id: device
    attributes:
      label: Device
      description: On what device did you encounter this bug?
      placeholder: e.g. Pixel 6
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Android version
      description: What version of Android are you on?
      placeholder: e.g. Android 14
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: Droid-ify version
      description: Check in Settings -> Credits
      placeholder: e.g. v0.7.6
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste your logs below, or drag and drop a log file.
      value: |
        <details>
        <summary>Logs</summary>

        ```kotlin
        // paste logs here and remove this line
        ```

        </details>

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Repos you have added, things you've tried, etc.
      placeholder: Any other details that might help...
