name: Feature Request
description: Suggest a feature or improvement
title: "[Request] "
labels: [ "enhancement" ]
type: feature
body:
  - type: markdown
    attributes:
      value: Feature request for Droid-ify

  - type: checkboxes
    id: checklist
    attributes:
      label: Guidelines
      description: Confirm before submitting
      options:
        - label: I have searched the issue tracker for [open](https://github.com/Droid-ify/client/issues) and [closed](https://github.com/Droid-ify/client/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
          required: true
        - label: I'm not requesting app support for a specific repo — that's up to repo maintainers
          required: true
        - label: I understand this might not get built (Droid-ify is maintained by a single person)
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What's missing for you?
      placeholder: e.g. I'm always having to... when...

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe your ideal solution
      placeholder: It would be great if...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Extras
      description: Screenshots, mockups, or extra context for the feature
      placeholder: Whatever might help us understand...
